[package]
name = "turl-cli"
version = "0.0.2"
edition = "2024"

[[bin]]
name = "turl"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
turl-core = { path = "../turl-core" }

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
tempfile = "3.23.0"
